modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-2.1-or-later"

[[mods]]
modId="tab_layouts"
version="${mod_version}"
displayName="Creative Tab Layouts"
logoFile="logo.png"
authors="Ziver1246"
updateJSONURL="https://raw.githubusercontent.com/Ziver1246/Ziver1246-Modding/main/Creative_Tab_Layouts/creative_tab_layouts-updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/creative-tab-layouts"
description='''
Adds page-based organization to Creative Tabs, allowing modders to group items into structured pages, subtabs, and collapsible sections with visual headers, banner pages, custom layouts, JSON-driven visuals, and optional sprite animations.

Includes a lightweight public API for building and extending layouts, querying resolved layout data, and reusing CTL headers and banners in external interfaces.

Designed to improve navigation and presentation for large, content-heavy mods while remaining simple to integrate.
'''

[[mixins]]
config="tab_layouts.mixins.json"


[[dependencies.tab_layouts]]
modId="neoforge"
mandatory=true
versionRange="[21.1.230,)"
ordering="NONE"
side="BOTH"

[[dependencies.tab_layouts]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
