modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-2.1-or-later"

[[mods]]
modId="tab_layouts"
version="1.0.0"
displayName="Creative Tab Layouts"
logoFile="logo.png"
authors="Ziver1246"
displayURL="https://www.curseforge.com/minecraft/mc-mods/creative-tab-layouts"
description='''
Adds page-based organization to Creative Tabs, allowing modders to group items into structured sections with visual headers, banner pages, custom layouts, JSON-driven visuals, and optional sprite animations.

Designed to improve navigation and presentation for large content-heavy mods while remaining simple to integrate through a lightweight API.
'''

[[mixins]]
config="tab_layouts.mixins.json"


[[dependencies.tab_layouts]]
modId="neoforge"
mandatory=true
versionRange="[21.1.210,)"
ordering="NONE"
side="BOTH"

[[dependencies.tab_layouts]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
